on:
  workflow_run:
    workflows: [Run tests]
    types: [completed]
    branches: [staging]
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    secrets: inherit
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: ./.github/workflows/deploy.yml
      with:
        environment: staging