on:
  workflow_run:
    workflows: [Run tests]
    types: [completed]
    branches: [master]
jobs:
  deploy-prod:
    secrets: inherit
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production